[package]
name = "holylib"
version = "0.1.0"
edition = "2024"

[dependencies]
gif = "0.13.3"
image = {version = "0.25.6", features = ["gif"]}
rand = "0.9.2"
x11 = {version = "2.21.0", features = ["xlib"]}
